version: '3'
services:
  app:
    image: yogamed
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=7wXDd5b9ZuwIFWGL
      - MONGODB_DATABASE=Cluster0
      - MONGODB_CONNECTION_STRING=mongodb://mongo/yogamed
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./__tests__:/app/__tests__
  mongo:
    image: mongo
    ports:
      - 27017:27017
